[package]
name = "rump-problem"
version = "0.1.0"
authors = ["Yuma Hiramatsu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlib = "0.5"
rug = "1.6"
